# Generated by Django 2.1.7 on 2019-03-02 15:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('locations', models.ManyToManyField(related_name='location', to='weatherapi.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateField(default=datetime.date(2019, 3, 2))),
                ('value', models.FloatField()),
                ('location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='weatherapi.Location')),
                ('metric', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='weatherapi.Metric')),
            ],
        ),
    ]
