# Generated by Django 4.0 on 2021-12-13 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='measured_at',
            field=models.DateField(default=datetime.date(2021, 12, 13)),
        ),
    ]
